---
# tasks file for webserver
- name: installing httpd package
  package:
     name: "httpd"
     state: present
     
- name: Copying content to webserver
  copy:
          
     content: " hello from {{ ansible_hostname }}"
     dest: "/var/www/html/index.html"

- name: starting web services
  service:
     name: "httpd"
     state: started
     enabled: yes


